button:
 -
  type: "click"
  name: "我的闻道"
  key:  "MY_WENDAO"
 -
  type: "view"
  name: "关于"
  url:  "http://wendao.easybird.cn/results/my_videos?user=#{request[:FromUserName]}"


# RAILS_ENV=production bundle exec  wechat menu_create /var/www/askdao_backend/shared/config/wechat_menu.yml
